<?php
/**
 * Tweakwise (https://www.tweakwise.com/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   Proprietary and confidential, Unauthorized copying of this file, via any medium is strictly prohibited
 */

namespace Tweakwise\Magento2TweakwiseExport\Test\Integration\Export\Product;

use Magento\Framework\Composer\ComposerInformation;
use Tweakwise\Magento2TweakwiseExport\Test\Integration\ExportTest;

/**
 * @magentoDbIsolation enabled
 * @magentoAppIsolation enabled
 */
class BasicTest extends ExportTest
{
    /**
     * Test if empty export does not throw error
     */
    public function testEmptyExport()
    {
        $file = __DIR__ . '/../../../../tests/data/integration/export/product/basic/empty.xml';
        //replace generated by placeholder in empty.xml
        $installedPackages = $this->composerInformation
            ->getInstalledMagentoPackages();
        $version = $installedPackages['tweakwise/magento2-tweakwise-export']['version'];
        $emptyFile = file_get_contents($file);
        $emptyFile = str_replace('GENERATED_BY', $version, $emptyFile);

        $this->assertEquals($emptyFile, (string) $this->exportFeed());
    }

    /**
     * Test export with one product and check on product data
     */
    public function testOneProduct()
    {
        $product = $this->productData->create();
        $feed = $this->exportFeed();

        $feedProduct = $feed->getProduct($product->getId());
        $feedProduct->assertSku($product->getSku());
        $feedProduct->assertName($product->getName());
        $feedProduct->assertPrice($product->getPrice());
        $feedProduct->assertAttributes([
            'sku' => $product->getSku(),
            'type_id' => 'simple',
            'tax_class_id' => 'Taxable Goods',
        ]);
        $feedProduct->assertCategories([100012]);
    }
}
